_specver: 2

modpack:
  name: All of Fabric 5
  description: The latest & best of Fabric on 1.18.1. Performance, technology, magic & exploration!
  
install:
  mcVersion: 1.18.1
  loaderVersion: 0.12.12
  modpackUrl: https://media.forgecdn.net/files/3601/961/All-of-Fabric-5-0.2.11.zip
  installerUrl: https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.10.2/fabric-installer-0.10.2.jar
  
  ignoreFiles:
    - mods/optifine*.jar
    - resources/**
  additionalFiles:
  localFiles: ~
  
  installerArguments:
    - "server"
    - "-downloadMinecraft"
    - "-snapshot"
    - "-mcversion"
    - "1.18.1"
    - "-loader"
    - "0.12.12"
  modpackFormat: curse
  formatSpecific:
    ignoreProject: []
  baseInstallPath: ~
  checkFolder: yes
  installLoader: yes
  spongeBootstrapper: ~

launch:
  # specifies the max amount of ram the server is supposed to launch with (Xmx)
  maxRam: 4G
  # specifies the minimal amount of ram the server is supposed to launch with (Xms)
  minRam: 4G
  # specifies whether the server is supposed to auto restart after crash
  autoRestart: yes
  javaArgs:
    - "-server"
    - "-XX:+UseG1GC"
    - "-XX:+ParallelRefProcEnabled"
    - "-XX:MaxGCPauseMillis=100"
    - "-XX:+UnlockExperimentalVMOptions"
    - "-XX:+DisableExplicitGC"
    - "-XX:+AlwaysPreTouch"
    - "-XX:G1NewSizePercent=30"
    - "-XX:G1MaxNewSizePercent=40"
    - "-XX:G1HeapRegionSize=8M"
    - "-XX:G1ReservePercent=20"
    - "-XX:G1HeapWastePercent=5" 
    - "-XX:G1MixedGCCountTarget=4" 
    - "-XX:InitiatingHeapOccupancyPercent=15" 
    - "-XX:G1MixedGCLiveThresholdPercent=90" 
    - "-XX:G1RSetUpdatingPauseTimePercent=5" 
    - "-XX:SurvivorRatio=32" 
    - "-XX:+PerfDisableSharedMem" 
    - "-XX:MaxTenuringThreshold=1" 
    - "-Dusing.aikars.flags=https://mcflags.emc.gs" 
    - "-Daikars.new.flags=true"
    
  spongefix: no
  ramDisk: no
  checkOffline: no
  crashLimit: 10
  crashTimer: 60min
  preJavaArgs: ~
  startFile: fabric-server-launch.jar
  forcedJavaPath: ~


